name = "dac"
main = "worker/index.ts"
compatibility_date = "2023-04-26"

[durable_objects]
bindings = [
  { name = "COUNTER", class_name = "Counter" } # Binding to our DurableObjectExample class
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Counter"]
