name = "dac"
main = "src/worker.ts"
compatibility_date = "2023-04-26"
compatibility_flags = [ "nodejs_compat" ]

[durable_objects]
bindings = [
  { name = "COUNTER", class_name = "Counter" } # Binding to our DurableObjectExample class
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Counter"]
