name: Deploy Worker

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          preCommands: npm install
          command: publish --keep-vars $([ "$GITHUB_REF_NAME" = "main" ] || echo "--env=$GITHUB_REF_NAME")
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: "2.17.0"
